-- =============================================================================
--  OFFICIAL HYPRLAND LUA PRODUCTION CHASSIS (v0.55.4 NATIVE)
--  Aesthetic: Premium Minimalist Matte Black / Rounded Corners
--  NOTE: This is a hyprland.lua style config (uses the `hl` API). NOT a .conf.
-- =============================================================================

-- User refresh-rate helper:
-- - Default fallback is 60 Hz.
-- - To use a different refresh rate (e.g. 180), set env HYPR_REFRESH=180 before Hyprland starts.
local REFRESH = tonumber(os.getenv("HYPR_REFRESH")) or 60
local WIDTH, HEIGHT = 1920, 1080
local MODE = string.format("%dx%d@%d", WIDTH, HEIGHT, REFRESH)

hl.config({
    autogenerated = false
})

-- 1. MONITOR HARDWARE PIPELINE
-- output = "" leaves monitor output blank => Hyprland will try to auto-detect.
-- To force a specific connector, replace "" with e.g. "DP-1" or "eDP-1".
hl.monitor({
    output = "",                 -- leave blank to auto-detect, or set your connector name
    mode = MODE,                 -- auto uses WIDTHxHEIGHT@REFRESH
    position = "0x0",
    scale = 1,
})

-- 2. CORE DAEMONS & SYSTEM AUTOSTART
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar &")
    hl.exec_cmd("dunst &")
    hl.exec_cmd("hyprpaper &")
    hl.exec_cmd("/usr/lib/xdg-desktop-portal-hyprland &")
end)

-- 3. ENVIRONMENT LOGIC
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- 4. MATTE STYLING, DWINDLE TILING, & ROUNDED CORNERS FIXED
hl.config({
    general = {
        gaps_in = 6,
        gaps_out = 14,
        border_size = 2,
        ["col.active_border"] = "rgba(ffffffff)",   -- Solid crisp white focus ring
        ["col.inactive_border"] = "rgba(1a1a1acc)", -- Deep charcoal frame
        layout = "dwindle"
    },

    decoration = {
        rounding = 14,                              -- Smooth rounded corners
        active_opacity = 1.0,
        inactive_opacity = 0.88,
        blur = {
            enabled = true,
            size = 8,
            passes = 3
        }
    },

    dwindle = {
        preserve_split = true,
        smart_split = false
    },

    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
        vrr = 1
    },

    animations = {
        enabled = true
    }
})

-- 5. FUNCTIONAL SYSTEM CORE BINDINGS (v0.55.4 EXPLICIT TWO-ARG SYNTAX)
hl.bind("SUPER + Q", hl.dsp.exec_cmd("kitty"))
hl.bind("SUPER + R", hl.dsp.exec_cmd("rofi -show drun"))
hl.bind("SUPER + C", hl.dsp.window.close())
hl.bind("SUPER + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + F", hl.dsp.window.fullscreen())

-- Launch Nemo File Manager
hl.bind("SUPER + E", hl.dsp.exec_cmd("nemo"))

-- Take Screenshot (Fixed syntax)
hl.bind("SUPER + PRINT", function()
    hl.exec_cmd("grim - | wl-copy && dunstify 'Screenshot copied' 'Full screen in clipboard'")
end)

-- Toggle screen recording (Saves to your Videos directory)
hl.bind("SUPER + End", hl.dsp.exec_cmd("pkill -SIGINT wf-recorder || wf-recorder -f ~/Videos/recording_$(date +%Y-%m-%d_%H-%M-%S).mp4"))

-- 6. MOUSE DRAG & RESIZE BINDINGS (SUPER + V HANDLERS & SPECIAL SYS)
-- Super + V + Left Click to drag/move window
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })

-- Super + V + Right Click to resize window
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Arrow Key Navigations
hl.bind("SUPER + left",  hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + right", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + up",    hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + down",  hl.dsp.focus({ direction = "down" }))

-- Vim HJKL Navigations
hl.bind("SUPER + H", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + L", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + K", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + J", hl.dsp.focus({ direction = "down" }))

-- Static Virtual Workspace Routing Loops (1 to 10)
for i = 1, 10 do
    local keyStr = tostring(i % 10)
    hl.bind("SUPER + " .. keyStr, hl.dsp.focus({ workspace = tostring(i) }))
    hl.bind("SUPER + SHIFT + " .. keyStr, hl.dsp.window.move({ workspace = tostring(i) }))
end

-- Emergency Exit
hl.bind("SUPER + ESCAPE", hl.dsp.exit())

hl.on("hyprland.start", function ()
    -- optional wallpaper fallback. hyprpaper is already started above; uncomment if you prefer swaybg
    -- hl.exec_cmd("swaybg -i /home/debian/Downloads/wallpaper.jpg -m fill")
end)

-- 7. APPLICATION SPECIFIC WINDOW RULES
-- Locks Nemo to exactly 50% opacity when active/inactive to show the underlying blur
hl.window_rule({
    name = "nemo-opacity",
    match = { class = "nemo" },
    opacity = "0.50 override 0.50 override 1.0 override"
})
